id: IFD41F742
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-05T19:56:40.661600'
last_modified: '2022-06-05T19:56:40.661605'
parser: null
source_metadata:
  title: Shamar Chökyi Wangchuk
  language: pt
  description: Texts by and about Shamar Chökyi Wangchuk (zhwa dmar chos kyi dbang
    phyug, 1584–1630), the sixth Shamarpa incarnation, famous for his journey to the
    Kathmandu Valley and the detailed observations he recorded there.
  volume:
    f49EB:
      title: Prayer of Aspiration Towards Sukhāvatī
      base_file: f49EB.txt
      order: 1
      parent: Aspiration Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
